name: Cinema CI

on:
  push

env:
  IS_MASTER: ${{ github.ref == 'refs/heads/master' }}

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
          source-url: https://nuget.pkg.github.com/derekdombek/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          dotnet restore ./CinemaApi/
          dotnet build ./CinemaApi/

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Container
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 722647055695.dkr.ecr.us-east-1.amazonaws.com
          docker build -f ./deployment/docker/CinemaApi/Dockerfile -t 722647055695.dkr.ecr.us-east-1.amazonaws.com/cinema-repo .
          docker push 722647055695.dkr.ecr.us-east-1.amazonaws.com/cinema-repo